---
title: "Entregable 5"
author: "Àlex Batlle Casellas"
date: "26/05/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
setwd("C:/Users/alexb/apunts/Q6/EST/problemes+pràctiques/entregable-5")
```

#### READ DATA:

```{r}
dd <- read.csv2("dades.csv")
head(dd)
answers <- NULL
alpha <- 0.05
#dim(dd)
```

#### Pregunta 1
```{r}
m1 <- lm(bodyfat~Weight+Neck+Chest+Abdomen+Knee, dd)
(s <- summary(m1))

# Apartat 1
r.sq.m1 <- s$r.squared
answers <- c(answers, r.sq.m1)

# Apartat 2
residual.variance <- s$sigma^2
answers <- c(answers, residual.variance)

# Apartat 3
intercept.m1 <- s$coefficients[1,1]
answers <- c(answers, intercept.m1)

# Apartat 4
f.stat.m1 <- s$fstatistic[1]
answers <- c(answers, f.stat.m1)

# Apartat 5
p.value.weight.m1 <- s$coefficients[2, 4]
answers <- c(answers, p.value.weight.m1)

# Apartat 6
vifs.m1 <- vif(m1)
max.vif <- max(vifs.m1)
answers <- c(answers, max.vif)

# Apartat 7
m.dummy <- NULL
#     Primer eliminem Chest perquè té el p-valor més alt
summary(m.dummy <- lm(bodyfat~Weight+Neck+Abdomen+Knee, dd))
#     Ara eliminem Neck perquè té el p-valor més alt
summary(m.dummy <- lm(bodyfat~Weight+Abdomen+Knee, dd))
#     Ara eliminem Knee perquè té el p-valor més alt
summary(m.dummy <- lm(bodyfat~Weight+Abdomen, dd))
# Ens quedem amb aquest model, atès que totes les variables que hi queden són significatives
m2 <- lm(bodyfat~Weight+Abdomen, dd)
number.of.variables.m2 <- m2$rank - 1
answers <- c(answers, number.of.variables.m2)

# Apartat 8
omnibus.test <- anova(m1, m2)
p.value.compare.m1.m2 <- omnibus.test$`Pr(>F)`[2]
answers <- c(answers, p.value.compare.m1.m2)

# Apartat 9
prop <- length(which(abs(rstudent(m2)) >= 2))/200
answers <- c(answers, prop)
plot(predict(m2), rstudent(m2))
abline(h=c(-2,0,2),lty=2)

# Apartat 10
cook.dist.m2 <- cooks.distance(m2)
max.dist.m2 <- max(cook.dist.m2)
answers <- c(answers, max.dist.m2)

# Apartats 11, 12, 13, 14
proposed.data <- list("Weight"=175.3, "Abdomen"=91.4)
prediction.with.pred.intervals <- predict(m2, newdata = proposed.data, interval = "prediction", level = 0.95)
prediction.with.conf.intervals <- predict(m2, newdata = proposed.data, interval = "confidence", level = 0.95)
# 11
lwr.pred <- prediction.with.pred.intervals[2]
# 12
upr.pred <- prediction.with.pred.intervals[3]
# 13
lwr.conf <- prediction.with.conf.intervals[2]
# 14
upr.conf <- prediction.with.conf.intervals[3]
# answers
answers <- c(answers, lwr.pred, upr.pred, lwr.conf, upr.conf)
```

#### Pregunta 2
```{r}
# Per a la segona part, considera la variable resposta bodyfat respecte el factor tractament Diet i la covariable Weight
dd$Diet <- as.factor(dd$Diet)
m3 <- lm(bodyfat~Diet, dd, contrasts = list(Diet = "contr.treatment"))
(s <- summary(m3))

# Apartat 15
intercept.m3 <- s$coefficients[1,1]
answers <- c(answers, intercept.m3)

# Apartat 16
r.sq.m3 <- s$r.squared
answers <- c(answers, r.sq.m3)

# Apartat 17
coeff.std.error.m3 <- s$coefficients[2,2]
answers <- c(answers, coeff.std.error.m3)

# Apartats 18, 19
library(emmeans)
(emm <- summary(emmeans(m3, ~Diet, at = list(Diet = 'A'))))
# 18
lwr.conf.emmeans <- emm$lower.CL
# 19
upr.conf.emmeans <- emm$upper.CL
answers <- c(answers, lwr.conf.emmeans, upr.conf.emmeans)

# Apartats 20, 21
m4 <- lm(bodyfat~Weight*Diet, dd)
(s <- summary(m4))
# 20
residual.stdev.m4 <- s$sigma
# 21
adj.r.sq.m4 <- s$adj.r.squared
answers <- c(answers, residual.stdev.m4, adj.r.sq.m4)

# Apartat 22
m4.add <- lm(bodyfat~Weight+Diet, dd)
anova(m4, m4.add)
f.stat.compare.m4.m4.add <- anova(m4, m4.add)$`F`[2]
answers <- c(answers, f.stat.compare.m4.m4.add)

# Ens quedem amb m4.add perquè anova ens indica que el model amb les interaccions no és significativament diferent d'aquest, i per tant ens quedem amb el model més senzill
summary(m4.add)
# Encara podríem reduïr més el model, però l'entregable no ens demana més coses
```

#### Finish the setup for the hand-in
```{r}
names(answers) <- NULL
dump("answers", file = "respostes.txt")
```

