all: hello hello2u hello2uchars integers inttrunc floats floatdiv ages

hello: hello.cc
	g++ -Wall -o hello hello.cc

hello2u: hello2u.cc
	g++ -Wall -o hello2u hello2u.cc

hello2uchars: hello2uchars.cc
	g++ -Wall -o hello2uchars hello2uchars.cc
	
integers: integers.cc
	g++ -Wall -o integers integers.cc
	
inttrunc: inttrunc.cc
	g++ -Wall -o inttrunc inttrunc.cc

floats: floats.cc
	g++ -Wall -o floats floats.cc

floatdiv: floatdiv.cc
	g++ -Wall -o floatdiv floatdiv.cc

ages: ages.cc
	g++ -Wall -o ages ages.cc

clean:
	rm -f hello hello2u hello2uchars integers inttrunc floats floatdiv ages
