all: hello hello2u

hello: hello.cc
	g++ -o hello hello.cc

hello2u: hello2u.cc
	g++ -o hello2u hello2u.cc

hello2uchars: hello2uchars.cc
	g++ -o hello2uchars hello2uchars.cc

clean:
	rm -f hello hello2u
